import type { NextPage } from 'next'
import Image from 'next/image'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { signIn, useSession } from 'next-auth/react';

import { SignInButton } from '../components/Buttons'

import styles from '../styles/Home.module.css'
import Dashboard from './app/dashboard';

const Home: NextPage = () => {
  const {data: session} = useSession();
  const router = useRouter()

  return (
    <div className={styles.container}>
      <Head>
        <title>CalvoBank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session ? (
        <Dashboard />
      ) : (
        <main className={styles.main}>
          {session }
          <Image 
            src='/calvologo.svg' 
            width={250}
            height={280}
            alt='calvologo'
          />
          <SignInButton onClick={() => router.push('/login')} />
        </main>
      )}
    </div>
  )
}

export default Home
